# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Data Science Foundation Curriculum
author: Daniel Kapitan
logo: jads-logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  allow_errors: true
  timeout: 120

launch_buttons:
  colab_url: "https://colab.research.google.com"

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/jads-nl/data-science-foundation-curriculum # Online location of your book
  branch: main  # Which branch of the repository should be used when creating links (optional)
  path_to_book: data_science_foundation_curriculum

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
